#!/bin/bash
WD=`pwd`
git pull
git diff
cd $WD/vladik/kernel/kernel
git pull
git diff
cd $WD/../../cg-miner-git/cgminer
git pull
git diff
cd $WD/../../minepeon/
git pull
git diff
cd $WD/../../u-boot/
git pull
git diff
cd $WD/spilib/
git pull
git diff

