#!/bin/sh

echo 51 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio51/direction
echo 1 > /sys/class/gpio/gpio51/value

echo 22 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio22/direction
echo 1 > /sys/class/gpio/gpio22/value
echo 0 > /sys/class/gpio/gpio51/value
 
prepare-emmc.sh
sync
echo 1 > /sys/class/gpio/gpio51/value 
echo 1 > /sys/class/gpio/gpio22/value 
sync
