#!/bin/bash
read number < ~/var.txt
let "number %= 10"
let "number += 1"
octeta=`printf %02x $number`
echo CMD[${octeta}] $@ 
echo CMD[${octeta}] $@ >> /dev/ttyUSB0
sleep 0.2
echo $number > ~/var.txt
