#ifndef _____DC2DEFINES__45R_H____
#define _____DC2DEFINES__45R_H____

// compilation flags
#define HAS_PLL 1
#define TEST_BOARD 0
#define NO_TOP 1


// System parameters
#define ASIC_TEMPERATURE_TO_SET_FANS_HIGH   ASIC_TEMP_95
#define MAX_ASIC_TEMPERATURE ASIC_TEMP_119

#define ASIC_TO_SET_FANS_HIGH_COUNT   1
#define MAX_FAN_LEVEL   100

#define RUNTIME_TO_START_CHANGING_VOLTAGES 60 // after 5 minute?


#define TIME_FOR_DLL_USECS  1000
#define MIN_COSECUTIVE_JOBS_FOR_SCALING 400
#define MAX_CONSECUTIVE_JOBS_TO_COUNT (MIN_COSECUTIVE_JOBS_FOR_SCALING+400)
#define MIN_COSECUTIVE_JOBS_FOR_AC2DC_MEASUREMENT MIN_COSECUTIVE_JOBS_FOR_SCALING
#define MIN_COSECUTIVE_JOBS_FOR_DC2DC_MEASUREMENT MIN_COSECUTIVE_JOBS_FOR_SCALING

// In seconds
#define BIST_PERIOD_SECS_RAMPUP            1
#define BIST_PERIOD_SECS                   5
#define TRY_ASIC_FREQ_INCREASE_PERIOD_SECS 30
#define HOT_ASIC_FREQ_DECREASE_PERIOD_SECS 9




#define AC2DC_TEMP_GREEN_LINE 110
#define AC2DC_CURRENT_TRUSTWORTHY (200)
#define AC2DC_CURRENT_LIMIT  1100
#define AC2DC_UPSCALE_TIME_SECS   60  //2 2 minutes wait before upscaling AC2DC 
#define AC2DC_SPARE_CURRENT_TO_UPSCALE 7
#define AC2DC_LEFT_CURRENT_TO_DOWNSCALE 5

#define AC2DC_CURRENT_JUMP_16S        (16)
#define AC2DC_CURRENT_MINIMAL_FOR_DOWNSCALE_16S        (16)
#define AC2DC_SCALING_SAME_LOOP_PERIOD_SECS  10 



#define DC2DC_TEMP_GREEN_LINE 90
#define DC2DC_POWER_TRUSTWORTHY      (2*16)
#define DC2DC_CURRENT_WARNING_16S (60 * 16)
#define DC2DC_CURRENT_TOP_BEFORE_LEARNING_16S (46 * 16) // TODO - for 6 ASICS
#define DC2DC_MINIMAL_TOP_16S (58 * 16) // never remember to current smaller then this 
#define DC2DC_INITIAL_CURRENT_16S (40 * 16) 
#define DC2DC_SAFE_TO_INCREASE_CURRENT_16S (1*16)
#define DC2DC_UPSCALE_TIME_SECS   30  



#define DC2DC_KEEP_FOR_LEAKAGE_16S    (1*16)
#define TIME_TO_RUN_AFTER_DC_PROBLEM  (3)

#define ASIC_VOLTAGE_DEFAULT ASIC_VOLTAGE_720
#define VTRIM_START VTRIM_MEDIUM

#define MAX_ASIC_FREQ ASIC_FREQ_870
#define MINIMAL_ASIC_FREQ ASIC_FREQ_225
#define ASIC_FREQ_SAFE ASIC_FREQ_435

#endif
