#ifndef _____DC2DEFINES__45R_H____
#define _____DC2DEFINES__45R_H____

// compilation flags
#define TEST_BOARD 0
#define ECONOMY 0


// System parameters
#define ASIC_TEMPERATURE_TO_SET_FANS_HIGH   ASIC_TEMP_89
// Above this not allowed
#define MAX_ASIC_TEMPERATURE ASIC_TEMP_119

#define ASIC_TO_SET_FANS_HIGH_COUNT   50
#define ASIC_TO_SET_FANS_LOW_COUNT    20


#define MAX_FAN_LEVEL                   100
#define HOT_ASICS_IN_LOOP_FOR_DOWNSCALE 6
#define COLD_ASICS_IN_LOOP_FOR_UPSCALE  4


#define TIME_FOR_DLL_USECS  1000
#define MIN_COSECUTIVE_JOBS_FOR_SCALING 400
#define MAX_CONSECUTIVE_JOBS_TO_COUNT (800)
#define MIN_COSECUTIVE_JOBS_FOR_AC2DC_MEASUREMENT MIN_COSECUTIVE_JOBS_FOR_SCALING
#define MIN_COSECUTIVE_JOBS_FOR_DC2DC_MEASUREMENT MIN_COSECUTIVE_JOBS_FOR_SCALING

// In seconds
#define BIST_PERIOD_SECS_RAMPUP            1
#define BIST_PERIOD_SECS                   15 
#define TRY_ASIC_FREQ_INCREASE_PERIOD_SECS 2



#define AC2DC_TEMP_GREEN_LINE 110
#define AC2DC_CURRENT_TRUSTWORTHY (10)
#define AC2DC_POWER_LIMIT  (1250)
#define AC2DC_UPSCALE_TIME_SECS   60  //2 2 minutes wait before upscaling AC2DC 

#define AC2DC_CURRENT_JUMP_16S        (16)
#define AC2DC_CURRENT_MINIMAL_FOR_DOWNSCALE_16S        (16)
#define AC2DC_SCALING_SAME_LOOP_PERIOD_SECS  5 



#define DC2DC_TEMP_GREEN_LINE         120
#define DC2DC_INITIAL_CURRENT_16S (60 * 16) 



#define VTRIM_550   0xFFC4
#define VTRIM_661   0xFFCF
#define VTRIM_664   0xFFD0
#define VTRIM_666   0xFFD1
#define VTRIM_669   0xFFD2
#define VTRIM_678   0xFFD6
#define VTRIM_676   0xFFD5
#define VTRIM_674   0xFFD4
#define VTRIM_671   0xFFD3
#define VTRIM_669   0xFFD2

#define VTRIM_810   0x10008

#define VTRIM_HIGH  0x0FFef
#if ECONOMY == 1
#define VTRIM_START 0x0FFbf
#else
#define VTRIM_START (VTRIM_661-2) //0x0FFd0//VTRIM_MIN//(0x0FFd0+10)//VTRIM_MIN //(0x0FFd2-7)//(0x0FFd2-0xf)
#endif


//#define CORNER_DISCOVERY_FREQ_SS       ASIC_FREQ_480 // all less




#define MAX_ASIC_FREQ ASIC_FREQ_840
#define MINIMAL_ASIC_FREQ ASIC_FREQ_225

#define AC2DC_BUG    1
#define IDLE_TIME_TO_PAUSE_ENGINES 4

#endif
