#!/bin/sh
#
# Miscellaneous.
#
# Written by Vladik Goytin.

rrd_dirs()
{
	[ -d /mnt/mmc-config/rrd ] && rm -rf /mnt/mmc-config/rrd
	mkdir /tmp/rrd
	cd /mnt/mmc-config
	ln -s /tmp/rrd ./
	cd /var/www
	ln -s /tmp/rrd ./
}

misc_start()
{
	rrd_dirs
}

led_init()
{
	echo 22 > /sys/class/gpio/export
	echo "on" > /sys/class/gpio/gpio22/direction
	echo 51 > /sys/class/gpio/export
	echo "on" > /sys/class/gpio/gpio51/direction
}

override_reboot() {
	rm /sbin/reboot
	echo "#!/bin/sh" > /sbin/reboot
	echo "echo REBOOT CALLED >> /mnt/mmc-config/log/messages" > /sbin/reboot
	echo "/usr/local/bin/spond-manager stop; sync; /bin/busybox reboot;" >> /sbin/reboot
	chmod 777 /sbin/reboot
}

case "$1" in
start)
	override_reboot
	misc_start
	led_init
	;;
stop)
	;;
restart|reload)
	"$0" stop
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

