#!/bin/sh
#
# Handle SPI.
#

export PATH=$PATH:/usr/local/bin

DAEMON=miner_starter

case "$1" in
start)
	# bullshit
	NORMALBOOT=1
	#	mount /mnt/sd-boot
	#	mount /mnt/mmc-config
	#	mount /mnt/mmc-boot

	if [ -e "/mnt/mmc-config/autorun" ]; then
		NORMALBOOT=0
		/mnt/mmc-config/autorun
	fi
	
	mount /mnt/sd-boot
	if [ -e "/mnt/sd-boot/autorun" ]; then
		NORMALBOOT=0
		/mnt/sd-boot/autorun
	fi
	umount /mnt/sd-boot

	echo "NORMALBOOT=${NORMALBOOT}"
	if [ ${NORMALBOOT} -eq 1 ]; then 
		read state < ${MINING_STATUS}
		[ ${state} -eq 1 ] && state='active' || state='passive'
		$0 stop
		${DAEMON} ${state} &
	fi
	;;
stop)
	${DAEMON} stop
	sleep 3
	;;
restart|reload)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?




