#!/bin/sh
#
# Miscellaneous.
#
# Written by Vladik Goytin.

rrd_dirs()
{
	[ -d /mnt/mmc-config/rrd ] && rm -rf /mnt/mmc-config/rrd
	mkdir /tmp/rrd
	cd /mnt/mmc-config
	ln -s /tmp/rrd ./
	cd /var/www
	ln -s /tmp/rrd ./
}

misc_start()
{
	rrd_dirs
}


case "$1" in
start)
	misc_start
	;;
stop)
	;;
restart|reload)
	"$0" stop
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

