#!/bin/sh
#
# Miscellaneous.
#
# Written by Vladik Goytin.

rrd_dirs()
{
	mkdir /tmp/rrd
	cd /var/www
	ln -s /tmp/rrd
}

misc_start()
{
	rrd_dirs
}


case "$1" in
start)
	misc_start
	;;
stop)
	;;
restart|reload)
	"$0" stop
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

