#!/bin/sh
#
# Handle SPI.
#

case "$1" in
start)
	echo "Setting hostname..."
	./bin/hostname baba
	;;
stop)
	;;
restart|reload)
	"$0" stop
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?



