#!/bin/sh
#
# Control lighttpd
#
# Written by Vladik Goytin.

. /etc/common-defs


start_lighttpd()
{
	lighttpd -f /etc/lighttpd.conf
}

stop_lighttpd()
{
	pkill lighttpd
}


case "$1" in
start)
	start_lighttpd
	;;
stop)
	stop_lighttpd
	;;
restart|reload)
	"$0" stop
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

