#!/bin/sh
#
# Handle SPI.
#

export PATH=$PATH:/usr/local/bin:/bin


case "$1" in
start)
	# bullshit
	NORMALBOOT=1
	#	mount /mnt/sd-boot
	#	mount /mnt/mmc-config
	#	mount /mnt/mmc-boot


	if [ -e "/mnt/mmc-config/autorun" ]; then
		NORMALBOOT=0
		/mnt/nfs/autorun
	fi


	if [ -e "/mnt/sd-boot/autorun" ]; then
		NORMALBOOT=0
		/mnt/sd-boot/autorun
	fi

	echo "NORMALBOOT=${NORMALBOOT}"
	if [ ${NORMALBOOT} -eq 1 ]; then 
		/usr/local/bin/spond-manager start
	fi
	;;
stop)
	/usr/local/bin/spond-manager stop
	;;
restart|reload)
	/usr/local/bin/spond-manager start
	/usr/local/bin/spond-manager stop
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?




