#!/bin/sh
#
# this is not a service, just a place to run anything that needs to happen on startup
#

case "$1" in
start|"")


	/etc/cron.d/pandp_register.sh &
	/etc/cron.d/RECORDHashrate    &


	;;

*)
	echo "This is a startup script, not a service, and it cannot be stopped or restarted.";;
esac


return $?
