#!/bin/sh
#
# Handle SPI.
#


MINERGATE_CMD="nohup chrt -f 90 /usr/local/bin/miner_gate_arm > /dev/null 2>&1"
CGMINER_CMD="nohup /usr/local/bin/cgminer --config /etc/cgminer.conf"
WATCHDOG_FILE="/var/run/dont_reboot"

export PATH=$PATH:/usr/local/bin:/bin




forever_mining_watchdog()
{
	while true
	do
		#sleep for 5 minutes
		sleep 300
		if [ -f $WATCHDOG_FILE ]
		then
			  echo "Removed watchdog file."
			  rm $WATCHDOG_FILE
		else
			  echo "Not mining, reboot!"
			  /usr/local/bin/spond-manager stop
			  sleep 1
			  reboot
		fi
		
	done
	
}



miner_gate_arm_watchdog () {
	$MINERGATE_CMD &
	echo $! > /var/run/miner_gate_arm.pid
	sleep 4
	$CGMINER_CMD &
	echo $! > /var/run/cgminer_arm.pid
	forever_mining_watchdog &
	echo $! > /var/run/fmw.pid

	while true; do
		pidm=`cat /var/run/miner_gate_arm.pid`
		if [ ! -e /proc/$pidm -a /proc/$pidm/exe ]; then
			echo "Minergate died and restarted"
			$MINERGATE_CMD &
			echo $! > /var/run/miner_gate_arm.pid
		fi

		pidc=`cat /var/run/cgminer_arm.pid`
		if [ ! -e /proc/$pidc -a /proc/$pidc/exe ]; then
			echo "Cgminer died and restarted"
			$CGMINER_CMD &
			echo $! > /var/run/cgminer_arm.pid
		fi
		sleep 3;
	done

}




start_mg() {
	
		if [ -f "/var/run/miner_gate_arm.pid" ]; then
			echo "minergate is already running"
		else
			miner_gate_arm_watchdog &
			echo $! > /var/run/miner_gate_arm_watchdog.pid
		fi
}


stop_mg() {
		if [ ! -f "/var/run/miner_gate_arm_watchdog.pid" ]
		then
			echo "Mining manager not running"
		else
			pid1=`cat /var/run/miner_gate_arm_watchdog.pid`
			pid2=`cat /var/run/cgminer_arm.pid`
			pid3=`cat /var/run/miner_gate_arm.pid`
			pid4=`cat /var/run/fmw.pid`
			kill $pid1
			kill $pid4
			kill $pid2
			kill $pid3
			rm /var/run/miner_gate_arm_watchdog.pid
			rm /var/run/miner_gate_arm.pid
			rm /var/run/cgminer_arm.pid
			rm /var/run/fmw.pid
		fi
}



case "$1" in
start)
	# bullshit
	NORMALBOOT=1

	#	mount /mnt/sd-boot
	#	mount /mnt/mmc-config
	#	mount /mnt/mmc-boot
	start_mg
	;;
stop)
	stop_mg
	;;
restart|reload)
	"$0" stop
	sleep 1
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?




