#!/bin/bash

if [ $# -lt 1 ] ; 
    then echo "$0 <miner-IP>"
    exit 1
fi
export SSHPASS=root
IMAGE="miner_gate/miner_gate_arm"
MINER=10.0.0.$1

if [ ! -e $IMAGE ] ;
	then echo "Image file $IMAGE not found"
	exit 2
fi
echo file $IMAGE exist


ping -c 1 $MINER > /dev/null 2>&1

if [ ! $? -eq 0 ] ; 
	then echo $MINER is not accessible
	exit 4
fi


echo $MINER accessible


sshpass -e ssh root@$MINER /usr/local/bin/spond-manager stop
sshpass -e scp $IMAGE root@$MINER:/usr/local/bin
sshpass -e ssh root@$MINER sync

