#!/bin/sh
CURDIR=${PWD}
vi add-ons/fs/fw_ver
cd ${CURDIR}/memtester-4.3.0/
make

#make latest miner swd
cd ${CURDIR}/../spilib/
./make_me

cd ${CURDIR}/../../../cg-miner-git/cgminer
make


#make buildroot
cd ${CURDIR}/buildroot-2013.05/
make

#make image
cd ${CURDIR}/kernel/kernel
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- uImage -j4
make ARCH=arm CROSS_COMPILE=arm-none-linux-gnueabi- spondoolies.dtb

#copy results
cd ${CURDIR}
cp  ${CURDIR}/kernel/kernel/arch/arm/boot/uImage ${CURDIR}/image/
cp  ${CURDIR}/kernel/kernel/arch/arm/boot/uImage ${CURDIR}/shar/data
cp  ${CURDIR}/kernel/kernel/arch/arm/boot/uImage ~/shared
cp  ${CURDIR}/kernel/kernel/arch/arm/boot/dts/spondoolies.dtb ${CURDIR}/image/

cp ${CURDIR}/image/* /srv/tftp/

#cp ${CURDIR}/image/* /media/zvisha/52D7-DCF8/; umount /media/zvisha/52D7-DCF8
echo "NOW DO:    cp ${CURDIR}/image/* /media/zvisha/*/; sleep 5 ; umount /media/zvisha/*"
