#!/bin/bash
. $(dirname $0)/constants

if [ $# -lt 3 ] ; 
    then echo "$0 <miner> <srcfile> <destfile> "
    exit 1
fi

RESTART="/usr/local/bin/spond-manager restart"
START="/usr/local/bin/spond-manager start"
STOP="/usr/local/bin/spond-manager stop"

MINER=$1
FILE_SRC=$2
FILE_TRG=$3
ping -c 1 -W 1 ${MINER} >/dev/null 2>&1
if [ ! $? -eq 0 ] ; then
	echo ${MINER},NO-PING
	exit 11
fi

#${SSHPASS_CMD} -o StrictHostKeyChecking=no ${MINER} cp ${FILE_TRG} ${FILE_TRG}.back
${SSHPASS_SCP} ${FILE_SRC} ${DEFAULT_USER}@${MINER}:${FILE_TRG}
RC=$?
${SSHPASS_CMD} ${DEFAULT_USER}@${MINER} ${RESTART}
if [ ! ${RC} -eq 0 ] ; then
	echo ${MINER},SCP-ERROR
	exit 12
else
	echo "${MINER},${FILE_TRG},`head -n 1 ${FILE_SRC}`"
fi

