#!/bin/bash
SHOW=0

if [ "$1" == "-show" ] || [ "$1" == "show" ]
then
	SHOW=1
	shift
fi

if [ $# -lt 3 ]
then
	echo "usage: $0 [-show] <scriptfile> <ipfile> params ..."
	exit 1
fi

WD=`dirname $0`
SCRIPT=$1
BIG_IP_LIST=$2
PARAMS=${@:3}

FILE_SIZE=`cat ${BIG_IP_LIST} |wc -l `

echo $FILE_SIZE
if [ $FILE_SIZE -gt 8 ] ; then
	DOSPLIT=TRUE
	/usr/bin/split -l 5 ${BIG_IP_LIST} ${BIG_IP_LIST}_
fi

if [ "${DOSPLIT}" == "TRUE" ] ; then
    echo SPLITS
    fnum=0
    for fn in ${BIG_IP_LIST}_*
    do
        fnum=$(($fnum+1))
        if [ ${SHOW} -eq 1 ] ; then
            apply_on_ips.sh ${SCRIPT} ${fn} ${PARAMS}  &
        else
            # lets clean previous log file
            rm -fr ${fn}.log
            apply_on_ips.sh ${SCRIPT} ${fn} ${PARAMS} > ${fn}.log &
        fi
    done
else
    if [ ${SHOW} -eq 1 ] ; then
        apply_on_ips.sh ${SCRIPT} ${BIG_IP_LIST} ${PARAMS}  
    else
        apply_on_ips.sh ${SCRIPT} ${BIG_IP_LIST} ${PARAMS} > ${BIG_IP_LIST}___.log 
    fi
fi

# lets wait for jobs to finish
for job in `jobs -p`
do
    echo "waiting for $job job to be finished"
    wait $job || let "FAIL+=1"
done

if [ ! ${SHOW} -eq 1 ]
then
# collects all outputs to one file
    rm -f ${BIG_IP_LIST}.log
    for fn in ${BIG_IP_LIST}_*.log
    do
        cat ${fn} >> ${BIG_IP_LIST}.log 
    done
    echo "Aggrigated results file - ${BIG_IP_LIST}.log" 
fi
