#!/bin/bash
. $(dirname $0)/constants

IP=$1
MINER_MON=$(wget http://admin:${WEB_PASS}@${IP}/monitor.php  --timeout=5  --tries=1 -O- 2> /dev/null)
echo ${MINER_MON} | jq . >/dev/null 2>&1
if [ ! $? -eq 0 ]
then
	wget --post-data "agree=true" "http://admin:${WEB_PASS}@${IP}/settings.php" > /dev/null 2>&1
	MINER_MON=$(wget http://admin:${WEB_PASS}@${IP}/monitor.php -O- 2> /dev/null)
fi
echo ${MINER_MON}

