#!/bin/bash
. $(dirname $0)/constants


IP=$1

. $(dirname $0)/pingver ${IP} -delay 3


#ping -c 1 -W 2 $IP > /dev/null 2>&1
#if [ $? -eq 0 ] ; then
#
#	FW=`${SSHPASS_CMD} ${DEFAULT_USER}@${IP} cat /fw_ver 2>/dev/null`
#	if [ $? -eq 0 ] ; then 
#		echo $IP,$FW
#	else
#
#		echo $IP,SSH-FAIL
#	fi
#
#else
#	echo $IP,NO-PING
#fi
