#!/bin/bash
. $(dirname $0)/constants

IP=$1
WAIT=1

if [ "$1" == "" ] || [ "$1" == "-delay" ] 
then
	echo "Usage: $(fname) <IP> [ -delay <delay-secs> ] "
	exit 1
fi

if [ "$2" == "-delay" ] ; then
	shift
	WAIT=$2
	shift
fi


ping -c 1 -W ${WAIT} ${IP} > /dev/null 2>&1
if [ $? -eq 0 ]
then
	FW=$(${SSHPASS_CMD} \
         ${DEFAULT_USER}@${IP} cat /fw_ver 2>/dev/null)
	if [ $? -eq 0 ]
    then 
		echo $IP,$FW
	else
		echo $IP,SSH-FAIL
	fi
else
	echo $IP,NO-PING
fi
