#!/bin/bash
. $(dirname $0)/constants

IP=$1

if [ "$2" == "" ] ; then
	WAIT=1
else
	WAIT=$2
fi

ping -c 1 -W ${WAIT} ${IP} > /dev/null 2>&1
if [ $? -eq 0 ]
then
	FW=$(${SSHPASS_CMD} -o ConnectTimeout=5 -o ConnectionAttempts=1 \
         ${DEFAULT_USER}@${IP} cat /fw_ver 2>/dev/null)
	if [ $? -eq 0 ]
    then 
		echo $IP,$FW
	else
		echo $IP,SSH-FAIL
	fi
else
	echo $IP,NO-PING
fi
