#!/bin/bash
IP=$1

ping -c 1 -W 1 ${IP} > /dev/null 2>&1
if [ $? -eq 0 ]
then
	FW=$(sshpass -p root ssh \
        -o StrictHostKeyChecking=no  \
        -o ConnectTimeout=5 \
        -o ConnectionAttempts=1 root@${IP} cat /fw_ver 2>/dev/null)
	if [ $? -eq 0 ]
    then 
		echo $IP,$FW
	else
		echo $IP,SSH-FAIL
	fi
else
	echo $IP,NO-PING
fi
