#!/bin/bash
. $(dirname $0)/constants

# argumnents:
#       1. cgminer conf template file
#       2. IP address of miner.
MINER_IP=$1
CGMINER_TMPLATE=$2

CGMINER_TRG=/etc/cgminer.conf
WID=WID
WIDTO=${MINER_IP}
SUBSTYPE=0
WD=`dirname $0`

stop_spond_manager() {
    ${SSHPASS_CMD} ${DEFAULT_USER}@${MINER_IP} /usr/local/bin/spond-manager stop
}

start_spond_manager() {
    ${SSHPASS_CMD} ${DEFAULT_USER}@${MINER_IP} /usr/local/bin/spond-manager start
}

big_or_equal_than_ref() {
	REF_SPLIT=(${CGMINER_TEMP_REF_VER//./ })
	COMP_VER=$(echo $1 | sed -e 's/\(.\)[^0-9\.].*/\1/')
	COMP_SPLIT=(${COMP_VER//./ })

	RC=1
	MAX_i=${#REF_SPLIT[@]}
	if [ ${#COMP_SPLIT[@]} -lt ${#REF_SPLIT[@]} ] ; then
		RC=0
		MAX_i=${#COMP_SPLIT[@]}
	fi

	for (( i=1; i<$MAX_i; i++ ))
	do
		if [ ${COMP_SPLIT[i]} -gt ${REF_SPLIT[i]} ] 
		then
			#echo "$COMP_VER BIGGER than $CGMINER_TEMP_REF_VER"
			break
		elif [ ${COMP_SPLIT[i]} -lt ${REF_SPLIT[i]} ] 
		then
			#echo "$COMP_VER smaller than $REF_VER"
			RC=0
			break
		fi
	done
	echo ${RC}
}

prep_for_old_ver() {
	#2. validate - somewhat that the template flie is correct
	IS_H=`cat ${CGMINER_TMPLATE} | jq .pools[].user 2>/dev/null | grep "%h" -c `
	IS_I=`cat ${CGMINER_TMPLATE} | jq .pools[].user 2>/dev/null | grep "%i" -c `

	if   [ ${IS_H} -eq 1 ]
	then
		SUBSTYPE=$((${SUBSTYPE}+1))
	elif [ ${IS_I} -eq 1 ]
	then
		SUBSTYPE=$((${SUBSTYPE}+2))
	fi

	if [ ${SUBSTYPE} -eq 0 ]
	then
		IS_USER=`cat ${CGMINER_TMPLATE} | jq .pools[].user 2>/dev/null`

		if [ $? -ne 0 ]
	    then
			echo "BAD template file  - not even a json.."
			exit 4
		fi 

		if [ "${IS_USER}" == "null" ]
	    then
			echo "BAD template file, no wallet entry!!"
			exit 5
		fi 
		echo "Couldnt find %h  or %i in wallet entry. using conf file without substitution"
	fi

	MINER_HOST_TEMP=`${SSHPASS_CMD} ${DEFAULT_USER}@${MINER_IP} sh -c "hostname"`
	MINER_HOST=${MINER_HOST_TEMP:6}

	CUSTOMFILE1=`mktemp`
	CUSTOMFILE2=`mktemp`

	# injecting miner ip, by replacing %i
	WID="%i"
	WIDTO=${MINER_IP}
	sed s/${WID}/${WIDTO}/g ${CGMINER_TMPLATE} > ${CUSTOMFILE1}

	# injecting miner hostname, by replacing %h
	WID="%h"
	WIDTO=${MINER_HOST}
	sed s/${WID}/${WIDTO}/g ${CUSTOMFILE1} > ${CUSTOMFILE2}
}

prep_for_new_ver() {
	echo "CGMINER_TRG=${CGMINER_TRG}.template"
	CUSTOMFILE2=`mktemp`
	CGMINER_TRG=${CGMINER_TRG}.template
	echo "cp ${CGMINER_TMPLATE} ${CUSTOMFILE}"
	cp ${CGMINER_TMPLATE} ${CUSTOMFILE2}
}


if [ $# -lt 2 ]
then
	echo Too Few Params
	echo "Usage: $(fname) <miner> <cgminer.conf.tmplfile> "
	exit 1
fi

# validation of prerequired data

#1. check that template file actually exists:
if [ ! -e ${CGMINER_TMPLATE} ] ; then
	echo File ${CGMINER_TMPLATE} Not Found.
	exit 2
fi

if [ $(big_or_equal_than_ref $(miner_ver ${MINER_IP})) -eq 1 ] 
then
	echo "Copying as Template cgminer.conf as is"
	prep_for_new_ver
else
	echo "Copying as regular cgminer.conf and performing subst"
	prep_for_old_ver
fi
 

# copy generated cgminer.conf to miner
echo "${WD}/cpfile ${MINER_IP} ${CUSTOMFILE2} ${CGMINER_TRG}"
${WD}/cpfile ${MINER_IP} ${CUSTOMFILE2} ${CGMINER_TRG}
rm -f ${CUSTOMFILE1} ${CUSTOMFILE2}


