#!/bin/bash
. $(dirname $0)/constants

MINER=$1
FILE2RM=$2
RESTART="/usr/local/bin/spond-manager restart"
ping -c 1 -W 1 ${MINER} >/dev/null 2>&1
if [ ! $? -eq 0 ] ; then
	echo ${MINER},NO-PING
	exit 11
fi

${SSHPASS_CMD} ${DEFAULT_USER}@${MINER} rm ${FILE2RM}
${SSHPASS_CMD} ${DEFAULT_USER}@${MINER} ${RESTART}

