#!/bin/bash

F2=/var/www/html/production/tmp/lastscan
if [ ! "$1" == "" ] ; then
	F2=$1
fi

IPFILE=/home/remo/scans/IPS-FULL-80-95-RANGE
F1=`mktemp`
/home/remo/miner_scripts/createdetected ${IPFILE} ${F1}
sleep 33
/home/remo/miner_scripts/perform_scan.sh ${F1} ${F2}
