#!/bin/bash

if [ $# -lt 2 ] ; 
    then echo "$0 <uImage_path> <miner-IP> [-check]"
    exit 1
fi
IMAGE=$1
MINER=$2
CHECK=$3
export SSHPASS=root

if [ ! -e $IMAGE ] ;
	then echo "Image file $IMAGE not found"
	exit 2
fi
echo file $IMAGE exist

strings $IMAGE | grep Linux-3.8.13  > /dev/null 2>&1

if [ ! $? -eq 0 ] ; 
	then echo "\n $IMAGE doesnt seem a valid image file. Aborting!"
	exit 3
fi
echo $IMAGE seem a valid image file. 

ping -c 1 $MINER > /dev/null 2>&1

if [ ! $? -eq 0 ] ; 
	then echo $MINER is not accessible
	exit 4
fi

echo $MINER accessible

if [ "$CHECK" == "-check" ] ; then
	echo -e "\n"
	read -p "....Push Image $IMAGE onto Miner $MINER ?" -n 1 -r
	echo    # (optional) move to a new line
	if [[ ! $REPLY =~ ^[Yy]$ ]] ; then
		echo Aborting
		exit 5
	fi
fi

echo sshpass -e ssh root@$MINER mount /mnt/mmc-boot
sshpass -e ssh root@$MINER mount /mnt/mmc-boot
echo sshpass -e scp $IMAGE root@$MINER:/mnt/mmc-boot/
sshpass -e scp $IMAGE root@$MINER:/mnt/mmc-boot/
echo sshpass -e ssh root@$MINER sync
sshpass -e ssh root@$MINER sync
echo sshpass -e ssh root@$MINER umount /mnt/mmc-boot
sshpass -e ssh root@$MINER umount /mnt/mmc-boot
sleep 3
echo sshpass -e ssh root@$MINER /sbin/reboot
sshpass -e ssh root@$MINER /sbin/reboot





