#!/bin/sh
echo 22 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio22/direction
echo 1 > /sys/class/gpio/gpio22/value

prepare-emmc
sleep 1
mount /mnt/sd-boot
mount /mnt/mmc-boot
cp /mnt/sd-boot/uImage /mnt/mmc-boot/
cp /mnt/sd-boot/spondoolies.dtb /mnt/mmc-boot/
umount /mnt/mmc-boot

echo 51 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio51/direction
echo 1 > /sys/class/gpio/gpio51/value

