#!/bin/sh

echo 51 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio51/direction
echo 1 > /sys/class/gpio/gpio51/value
sleep 1
echo 22 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio22/direction
echo 1 > /sys/class/gpio/gpio22/value
echo 0 > /sys/class/gpio/gpio51/value
 
umount /mnt/sd-boot 
umount /mnt/mmc-boot
prepare-emmc.sh
mount /mnt/sd-boot
mount /mnt/mmc-boot
cp /mnt/sd-boot/uImage /mnt/mmc-boot/
cp /mnt/sd-boot/spondoolies.dtb /mnt/mmc-boot/
umount /mnt/mmc-boot

echo 1 > /sys/class/gpio/gpio51/value 
echo 1 > /sys/class/gpio/gpio22/value 
